CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) UNIQUE NOT NULL,
    used_storage INT UNSIGNED NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_hash VARCHAR(200) NOT NULL
);

CREATE TABLE tokens (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(200) UNIQUE NOT NULL,
    expires TIMESTAMP NOT NULL,
    revoked TINYINT(1) NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE files (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    size INT UNSIGNED NOT NULL,
    uploaded TIMESTAMP NOT NULL,
    visibility VARCHAR(20) NOT NULL,
    path VARCHAR(300) UNIQUE NOT NULL,
    owner_id INT UNSIGNED NOT NULL,
    FOREIGN KEY(owner_id) REFERENCES users(id)
);

CREATE TABLE permissions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    file_id INT UNSIGNED NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(file_id) REFERENCES files(id)
);
